### ISSUE TITLE
运维管理 -> 告警-> 全局告警规则 与 官网文档不对应

### ISSUE THREAD

**Issue by AIinstar** [kubecube-io/kubecube-front#18]
KubeCube 版本1.1.0 admin 用户登录之后 
运维管理 -> 告警-> 全局告警规则 没有任何按钮 (**官网文档不对应**)，全局告警配置 不能新建

**Comment by sjm1202** [comment]
全局告警配置由部署脚本创建，且每个集群仅有一个全局告警配置，页面仅提供设置功能不提供新建功能，页面设置按钮不可用问题下个版本会修复
![image](https://user-images.githubusercontent.com/35730557/218632453-21375f01-67bf-4f1e-a614-72c75d87b4d5.png)
